from typing import Any

from collections.abc import Hashable, Iterable, Iterator, Mapping, Set

class NodeView(Mapping, Set):
    def __getitem__(self, n: Hashable) -> dict[Hashable, Any]: ...

class EdgeView(Mapping, Set):
    def __getitem__(self, e: Hashable) -> dict[Hashable, Any]: ...

class Graph(Iterable):  # doesn't really inherit from iterable, but is iterable
    @property
    def nodes(self) -> NodeView: ...
    @property
    def edges(self) -> EdgeView: ...

class DiGraph(Graph):
    def add_node(self, node_for_adding: Hashable, **attr: Any) -> None: ...
    def add_edge(self, u_of_edge: Hashable, v_of_edge: Hashable, **attr: Any) -> None: ...
    def predecessors(self, n: Hashable) -> Iterator[Hashable]: ...
    def successors(self, n: Hashable) -> Iterator[Hashable]: ...
    def reverse(self, copy: bool) -> DiGraph: ...

def topological_generations(graph: DiGraph) -> Iterator[list[Hashable]]: ...
def is_directed_acyclic_graph(graph: DiGraph) -> bool: ...
def reverse_view(graph: DiGraph) -> DiGraph: ...
def neighbors(G: DiGraph, n: Hashable) -> Iterator[Hashable]: ...
def bfs_tree(G: DiGraph, source: Hashable) -> DiGraph: ...
def induced_subgraph(G: DiGraph, nbunch: NodeView) -> DiGraph: ...
