name: Build

on:
  release:
    types: [ created ]
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]
        python: [ "3.11" ]
    uses: ./.github/workflows/setup.yml
    secrets: inherit
    with:
      os: ${{ matrix.os }}
      python: ${{ matrix.python }}
      command: make build && make publish
