name: Check

on: [ push, pull_request ]

jobs:
  check:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
        python: [ "3.9", "3.10", "3.11" ]
    uses: ./.github/workflows/setup.yml
    with:
      os: ${{ matrix.os }}
      python: ${{ matrix.python }}
      command: make test && make lint
